### ISSUE TITLE
en_short minutes and months indistinguishable

### ISSUE THREAD

**Issue by bigpresh** [pstuifzand/date-period-human#5]
For the language `en_short`, both minutes and months use the same format:

```
            time_months_ago             => '%dm ago',
            time_a_month_ago            => '1m ago',
...
            time_minute_ago             => '%dm ago',
            time_minutes_ago            => '%dm ago',
...
            time_in_minute              => 'in %dm',
            time_in_minutes             => 'in %dm',
...
            time_in_month               => 'in %dm',
            time_in_months              => 'in %dm',
```

This leads to confusion, for instance:

```
$ Date::Period::Human->new( { lang => 'en_short' })->human_readable(
    DateTime->now->subtract(minutes => 3)->datetime(' ')
);
3m ago
$ Date::Period::Human->new( { lang => 'en_short' })->human_readable(
    DateTime->now->subtract(months => 3)->datetime(' ')
);
3m ago
```

I think the natural solution is to change the months ones to an upper-case "M".

It would also be really useful if you could provide your own language classes for Date::Period::Human to use, e.g. if you set `lang => 'Foo'`, then it would first try to load Date::Period::Human::Format::Foo (and if found, make sure it can `human_readable()` then call that to get the result), and if not, fall back to looking for a language named 'Foo' in the hash of built-in language formats).

Even just exposing that hash of language formats in a way that a subclass (or dirty monkey-patcher :) ) could modify bits of it without having to copy & paste the whole of `human_readable` into the subclass would be enough, though.

**Comment by pstuifzand** [comment]
I created a new version 0.4.7 that has the translation in a package variable. Is this something you can work with?

**Comment by bigpresh** [comment]
That's perfect, thanks - that lets me poke at it in a simple way.

Also... I just looked at the changelog and realised it was *me* who submitted the en_short language strings a couple of years ago using "m" for both minutes and months...
 
![Homer pulls collar](https://lfgss.microco.sm/api/v1/files/a1aa9e05b402dd3d56eb7b1998950d049cb8dc5e.png)

**Comment by pstuifzand** [comment]
It's easy to forget! Thanks for the suggestion.
