### ISSUE TITLE
sprintf crashes/throws warning on some translation strings

### ISSUE THREAD

**Issue by isync** [pstuifzand/date-period-human#6]
> Redundant argument in sprintf at /usr/local/share/perl/5.28.1/Date/Period/Human.pm line 303

Whenever `_translate()` hits a string that does NOT contain a replacement placeholder like %d but `@values` holds some value, sprintf complains and crashes the module.
For example "time_a_week_ago".

Don't know when this started, under which Perl version, or so.. One would expect sprintf to simply ignore such cases...

Quick fix is to return early around line 303 (code messed up by markdown... for example escaped percent sign...):
>
>....
>    return $translation{$self->{lang}}{$key} if $translation{$self->{lang}}{$key} !~ /\%/;
>    return sprintf($translation{$self->{lang}}{$key}, @values);
>}

probably better (less ref look-ups... faster?)
> sub _translate {
>     my ($self, $key, @values) = @_;
> 
>         my $string = $translation{$self->{lang}}{$key};
>         return $string if $string !~ /\%/;
>         return sprintf($string, @values);
> }

**Comment by pstuifzand** [comment]
It seems there are warnings in these [test reports][reports]. I have also confirmed it locally, for 5.26.0.

[reports]: http://www.cpantesters.org/cpan/report/d677a6d0-6e99-11ea-9066-e374b0ba08e8

**Comment by pstuifzand** [comment]
I released version 0.4.8 that fixes this issue. It should appear on CPAN shortly.

**Comment by isync** [comment]
Thank you Peter!
